### ISSUE TITLE
Downoad

### ISSUE THREAD

**Issue by cjburkey01** [ThunderGemios10/Survival-Games#1]
Is there any download yet?  Sorry if this was an inconvenient place to put this, but I didn't know where else to ask.

**Comment by ThunderGemios10** [comment]
I'm working on it!

EDIT: Download is now available at: https://github.com/ThunderGemios10/Survival-Games/releases

**Comment by cjburkey01** [comment]
Sorry, just wanted to make sure :P

**Comment by ThunderGemios10** [comment]
@cjburkey01 Ok then. I plan on updating this and publishing this on Spigot soon. Look forward to it. But i might just maintain it for future versions of Minecraft. _cough_ 1.9 _cough_
