### ISSUE TITLE
Missing Perms

### ISSUE THREAD

**Issue by cjburkey01** [ThunderGemios10/Survival-Games#11]
I have given users all the perm they need, but they still can't use the sign wall or `/sg join 1` to join the arena.  I am actually using a version I compiled from the current available code, so I don't know if that's a strange result of that.

**Comment by cjburkey01** [comment]
Found the issue, `sg.arenas.join.NUMBER` is incorrect, but is still displayed in the README file.  Change it to `sg.arena.join.NUMBER`

**Comment by ThunderGemios10** [comment]
@cjburkey01 All right! I'll fix it up..

**Comment by cjburkey01** [comment]
Thanks :)
