### ISSUE TITLE
Bug - Permissions

### ISSUE THREAD

**Issue by TheIntelloBox** [ThunderGemios10/Survival-Games#22]
sg.arena.join.2
sg.arena.join.\* 
sg.arena.vote
sg.arena.spectate
sg.lobby.join

I give these permissions but my players can't join. Please help me.

**Comment by ThunderGemios10** [comment]
That's odd. It should be working.

What permission plugin are you using?

**Comment by TheIntelloBox** [comment]
Group Manager. :(

**Comment by ThunderGemios10** [comment]
Are you sure they are given to right group?

**Comment by TheIntelloBox** [comment]
Of course. I did the /manuaddp command with the permissions to a specific player. And after, I did /mangaddp group, and nothing work.

**Comment by TheIntelloBox** [comment]
I really need it. ;(

**Comment by ThunderGemios10** [comment]
@TheIntelloBox Unfortunately, I cannot help you. You may have to ask your friend or someone else for this kind of thing.

As because this is a problem on your end.

**Comment by TheIntelloBox** [comment]
Could you add : 

sg.arena.*
Or something like that ?

**Comment by sshipway** [comment]
FWIW I have tested out using PermissionsEX and it works, though you have to give sg.arena.join.1 explicitly rather than sg.arena.join.*
