### ISSUE TITLE
Commands cannot be run from the console

### ISSUE THREAD

**Issue by sshipway** [ThunderGemios10/Survival-Games#23]
Certain commands should be able to be run from the console.  For example, /hg start 1 20 to start the game, or hg disable and hg enable.  This would allow easier control without having to be actually in the game.  However currently all commands insist you run them when in-game, even if this should not be necessary as your status would be irrelevant.

The code needs to allow console access (player==null) for commands where it is irrelevant

**Comment by Remyk1** [comment]
I added this in commit 3b0565cc77b76e3b7230b37e6fae1917e6ae37c6.
Allowing the following commands to be run from the console:
forcestart, enable, disable, delarena, reload, resetarena, listarenas,
gecount, list and flag.
