### ISSUE TITLE
SG addwall not working

### ISSUE THREAD

**Issue by ghost** [ThunderGemios10/Survival-Games#26]
As I create an arena and get the selection on the signs, once I execute the /sg addwall X  command it doesn't show anything nor does anything happen when I right click the sign. I'm on 1.10.2 btw if that helps.

PS. I can join with the commands though.

**Comment by ThunderGemios10** [comment]
@Tamberlox Try /sg setwall or /sg setstatswall

**Comment by ghost** [comment]
I'll give it a try once I get back home.
Btw /listarenas doesn't work either.
Is it becuase I mixed the old sg plugin folder with the new plugin?

**Comment by ThunderGemios10** [comment]
@Tamberlox Probably, Try deleting the old one. And let the new one regenerate a new folder.

**Comment by ghost** [comment]
I'll let you know once I've tried fixing it. 
Thanks for your help 😊

**Comment by ghost** [comment]
It didn't work :\

**Comment by ThunderGemios10** [comment]
@Tamberlox Then, It's probably a bug. I will try finding the problem when i find time.

**Comment by ghost** [comment]
Alright, thanks a lot man 😄
