### ISSUE TITLE
Refill doesnt work

### ISSUE THREAD

**Issue by finlayhalliday** [ThunderGemios10/Survival-Games#27]
My chests dont seem to be getting refilled. is there a command to select the chests? please help i need this asap

**Comment by ThunderGemios10** [comment]
So far, You can only use /sg refill, Or you can go ahead and ask @sshipway about it.

**Comment by sshipway** [comment]
The chests should refill the first time they are opened by a player, or when the admin does `/sg refill`, or on a daily basis if you have it enabled in the config (though this is a bit weird).  When the refill happens it may or may not remove what is already in there.
It is a little counterintuitive that the chests are only refilled when opened by a player in the game.  So, if you are an admin not playing, or flying about when the game is not running, then the chests will not appear refilled, and will show their 'pre-open' state.  THis may contain the base items, or (if you have randomness) the first slot will contain coloured wool indicating the class of random items to add.  When the chest is first opened, during a game, by a player, then the wool will be removed (if there), and the appropriate random items added (if there was wool).
When a game ends, any chests that were opened during the game are reverted to their pre-opening state.  This means that, if you want to modify a chest, do it when not in a game, as an op.
