### ISSUE TITLE
Citezens support?

### ISSUE THREAD

**Issue by LadyHaley** [ThunderGemios10/Survival-Games#28]
Helloooo,

I was wondering if you would consider adding support for citizens so that of there are any empty spots after a certain amount of time they get filled with bots and the game begins. I know that would very likely be very hard but cant hurt to ask

**Comment by ThunderGemios10** [comment]
@DeathJusty That would be difficult to program. I currently have no plans to update Survival Games unless there's bugs. I might consider adding Citizen support in the near future.
