### ISSUE TITLE
Wall not adding arenas

### ISSUE THREAD

**Issue by shortlady** [ThunderGemios10/Survival-Games#31]
Hi, I made a new arena, it shows up in the /sg listarenas 1 as "2,"  but no sign is added to my lobbywall. Any ideas what I'm doing wrong? (spawnpoints were set, everything looks normal....)

Thanks!

**Comment by ThunderGemios10** [comment]
@shortlady I am having trouble understanding. Can you explain?

**Comment by ghost** [comment]
The same goes for me. After creating the arena the command "sg / addwall" tells me "wall added" but nothing happens

**Comment by ThunderGemios10** [comment]
@GeoGosh Are you talking about the "Walls" plugin or Survival Games?

**Comment by ghost** [comment]
![errrrrr](https://cloud.githubusercontent.com/assets/25985817/23331929/d8c3b5f0-fb6f-11e6-9a0c-5094e7a58b7a.png)
@ThunderGemios10  After creating the arena and lobby use the command "sg addwall" chat shows "Added Lobby Wall" but nothing appears
I do something wrong or is it a plugin problem?

**Comment by ThunderGemios10** [comment]
@GeoGosh /sg addwall has been deprecated.

Please use /sg setstatswall for future use.
