### ISSUE TITLE
Feature & Permission Issues

### ISSUE THREAD

**Issue by ghost** [ThunderGemios10/Survival-Games#34]
I have been working on setting up this plugin today and everything seems to be setup fine except the following. Keep in mind when "op" all arenas and commands work fine except the lobby wall

sg.arena.join.1 doesn't grant access to players to join the arena

When setting the lobby wall, nothing shows on the signs

**Comment by ThunderGemios10** [comment]
@nexlemav Did you grant players the following permissions ?

- sg.arena.join
- sg.arena.join.*

**Comment by ghost** [comment]
Yes I have those perm nodes added.

I was able to resolve the join addwall signs though. 

Still not sure why the /sg join 1 command isnt working.

**Comment by ThunderGemios10** [comment]
@nexlemav Any errors or stacktraces popping up in the console?]

EDIT: Try to add this permission:

- sg.lobby.join
