### ISSUE TITLE
Error on Startup and Wall Creation

### ISSUE THREAD

**Issue by TechnoGeek123-321** [ThunderGemios10/Survival-Games#35]
On server startup I get this error: http://pastebin.com/2h4Td0VZ
On stat wall creation, I get this error (I am unable to create stat walls): http://pastebin.com/9uKbVYSX
Thanks!

**Comment by Remyk1** [comment]
1.  We switched to bstats for metrics 
1.  /sg setstatswall was replaced by /sg addwall
