### ISSUE TITLE
Stats not showing up

### ISSUE THREAD

**Issue by AddictedFader** [ThunderGemios10/Survival-Games#36]
I am trying to create a leader board with /sg setstatswall and it says sent back error

**Comment by AddictedFader** [comment]
java.lang.NullPointerException
15.03 01:53:15 [Server] WARN at com.thundergemios10.survivalgames.stats.StatsWallManager.setStatsSignsFromSelection(StatsWallManager.java:131)
15.03 01:53:15 [Server] WARN at com.thundergemios10.survivalgames.commands.SetStatsWall.onCommand(SetStatsWall.java:12)
15.03 01:53:15 [Server] WARN at com.thundergemios10.survivalgames.CommandHandler.onCommand(CommandHandler.java:155)
15.03 01:53:15 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
15.03 01:53:15 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
15.03 01:53:15 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
15.03 01:53:15 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)

**Comment by ThunderGemios10** [comment]
@AddictedFader Please use 1.11+ and above.

**Comment by EvilOlaf** [comment]
Therefore this plugin is NOT compatible with 1.8-1.10 ?

SG 0.6.5 @ Spigot 1.8.8
