### ISSUE TITLE
Chest refill problems

### ISSUE THREAD

**Issue by sshipway** [ThunderGemios10/Survival-Games#4]
There seem to be some issues with the Chest Refill code (I'll try and search through the source for this later)
- We keep getting chests filled with ALL the options from the level 5 chest, which is obviously unbalanced.  We should be able to specify a random range of how many items are added to each chest each refill?
- The Chests do not do an initial fill at the start of the game.  It would be good to have an (optional?) refill at game start.
- In the chest.cfg, there is no way to specify object DV or metadata.  Thus it seems there is no way to put lapis in the chests (needed for  enchanting of course)
- It would be nice to be able to somehow tag chests as being more 'lucky' than others (eg, a hard to reach chest should be more likely to get tier 5 loot) but I'm not sure how you'd go about this.  Maybe if the chest has a name '5' then multiply the random number by 5?

Otherwise, all working well, a nice simple mod to provide the needed functionality.

**Comment by ThunderGemios10** [comment]
Same answer for #5

**Comment by sshipway** [comment]
Reference #8 
- There is no fill event as such, they are randomised when the chest is first opened (if the option is set).
- You CAN specify DV; it is just that the file format was undocumented.  chests.yml is the same as kits.yml for parsing
- This can be done by a wool item in slot 0 (undocumented) but only works on first reset.  Am trying to make patch to handle this correctly.

**Comment by sshipway** [comment]
Fixed in #10 . Needs more documentation.

**Comment by ThunderGemios10** [comment]
@sshipway You can make a document for it, At https://github.com/ThunderGemios10/Survival-Games/wiki

The wiki can be edited by anyone, and has no restrictions.

**Comment by sshipway** [comment]
I'll see if I can add something tomorrow.  In the meantime, I've been expanding out the README.md

**Comment by sshipway** [comment]
Closing because chest refill issue now solved; documentation and other Inventory-items in separate issues
