### ISSUE TITLE
/Sg forcestart won't work! please answer asap!

### ISSUE THREAD

**Issue by vikscer** [ThunderGemios10/Survival-Games#41]
I am trying to force start a game, so i first enter "/sg help staff"
there it sayt that to force start game i gotta use /sg forcestart.
BUT WHEN I DO, it says that the command doesnt exist. PLEASE HELP ASAP
Thank ya bois
btw
Great plugin
great job
10/10
i just need the force start to use :D

**Comment by ThunderGemios10** [comment]
Do you get any errors on the console?

**Comment by iTzRockGamez** [comment]
instead use ./sg start (arena)
