### ISSUE TITLE
Knockback Enchantment Breaks Plugin

### ISSUE THREAD

**Issue by UKCPirate** [ThunderGemios10/Survival-Games#43]
Using the knockback enchantment, in kits or chests, returns an error in console and breaks the plugin.

Chests.yml - https://pastebin.com/vcG8c727

Console Output - https://pastebin.com/yPVWVd7B

**Comment by UKCPirate** [comment]
I got it working by adding the following into ItemReader

		encids.put("knockback", Enchantment.KNOCKBACK);

**Comment by Remyk1** [comment]
You fixed this in #45 
So i'll just close this issue
