### ISSUE TITLE
Can't PvP

### ISSUE THREAD

**Issue by Expedect** [ThunderGemios10/Survival-Games#47]
It's not a WorldGuard problem, already checked.

It's also not a server problem since I can PvP in other worlds.

Please help

**Comment by ThunderGemios10** [comment]
Are you sure you setup the arena correctly?

**Comment by Expedect** [comment]
Well, I really couldn't find any proper tutorials, maybe you could help me out a little bit?

I setup the arena, set the spawn spots and added the sign area. I didn't set up perms, but my opped players are playing so I don't believe that's the problem.

Thank you for your response, glad the Dev actually cares for their plugin and its users!

**Comment by ThunderGemios10** [comment]
You can find old tutorials for the plugin when Double0Negative still maintained the plugin. It's basically the same process with a few exceptions.

**Comment by Expedect** [comment]
I will check it out.
