### ISSUE TITLE
Support for string item IDs in chest.yml and kits.yml

### ISSUE THREAD

**Issue by sshipway** [ThunderGemios10/Survival-Games#5]
This should be pretty easy to do in ItemReader, if I read it correctly.
Then items from mods would be able to be added without it being dependent on module load order.

**Comment by ThunderGemios10** [comment]
Thanks for the suggestion, Right now, I got my hands full on some projects, If you would like to help out, Fork and create a pull request for it.

**Comment by sshipway** [comment]
Well, Java isn't really my language, and I've only worked with Forge mods and not Bukkit so far, but I'll give it a go.

I'm still trying to work out how the arena reset works after a game finishes and you need to put everything back how it was... I can't see how the contents of dispensers and chests is reset, as the code seems to be commented out?

Several things seem a bit confusing - how do Bandages work? how does the Wool block in chests work? how do resets work? - and some could do with more userfriendliness - command error messages, status messages, flags, config functions.  There is a huge need for more documentation; I know this isn't your fault, it was like that when you forked the project... but the original project seems dead and your fork still lives ;)

**Comment by ThunderGemios10** [comment]
Yes, I'm not very good at documenting plugins, I'll look forward to the PR.

**Comment by sshipway** [comment]
I have this working via class names ( so, diamond_sword and DIAMOND_SWORD work, but minecraft:diamond_sword does not ) and the `Material.matchMaterial()` call.  Also, much more error trapping in the parser which is really fragile (sloppy coding by 00-ve on this one I think)

Pull req to come soon

**Comment by sshipway** [comment]
Fixed in #10
