### ISSUE TITLE
Can not PVP

### ISSUE THREAD

**Issue by xan61789** [ThunderGemios10/Survival-Games#51]
Players can not be PVP
No damage at all
Can not delete the existing arena
This is my configuration

################################################
#               Survival Games                 #
#                                              #
#                Developed by                  #
#           ## Original Author ##              #
#              Double0negative                 #
#           ## Current Author ##               #
#             ThunderGemios10                  #
#                                              #
#                                              #
#              http://mc-sg.org                #
#                 voidmc.com                   #
################################################

#Do NOT touch this!
config-version: 3

#Enable debug messages
debug: false

#Enables the udpdate checker. This will enabled
#anyone with the perm sg.system.updatenotify to
#be notified when a new update is avalible
check-for-updates: true

#Set how many players are needed for the game
#to auto-start. Once the player limit is reached
#it will wait for x amount of seconds for
#additional players. Auto start vote means that
#x percent of players need to vote with /sg vote
#for the game to begin
auto-start-players: 12
auto-start-time: 10
auto-start-vote: 75

#If the player queue is enabled then if a player
#tries to join a game that is not joinable
#(ie ingame) the player will be added to a
#queue line to join the next time the game
#is open
enable-player-queue: true

#If set to true, commands not associated with
#the Survival Games will not be allowed to be run 
#by players in-game.
disallow-commands: true
#If disallow-commands is set to true, you can use
#the cmdwhitelist section below to whitelist certain
#commands.
cmdwhitelist: 
- 'kit' 

#Set how long the grace period for be after the start of 
#the game in seconds.
grace-period: 1800

#Controls if chests should be restocked on the first
#night. If set to true this will also have the side
#effect of setting the world time to day at the start
#of the game. This is only temporary until per-arena time
#has been implemented.
restock-chest: true
# Restock EVERY night?
restock-chest-repeat: false
# Remove all items from chests when adding random content?
clear-chest: false

#Here you can control block placing and breaking. 
block:
  place:
    whitelist:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 35
    - 37
    - 38
    - 39
    - 40
    - 41
    - 42
    - 44
    - 45
    - 47
    - 48
    - 50
    - 51
    - 53
    - 54
    - 55
    - 56
    - 57
    - 58
    - 59
    - 60
    - 61
    - 63
    - 64
    - 65
    - 66
    - 67
    - 68
    - 69
    - 70
    - 71
    - 72
    - 73
    - 75
    - 77
    - 78
    - 79
    - 80
    - 81
    - 82
    - 83
    - 84
    - 85
    - 86
    - 91
    - 92
    - 93
    - 94
    - 96
    - 98
    - 99
    - 100
    - 101
    - 102
    - 103
    - 104
    - 105
    - 106
    - 107
    - 108
    - 109
    - 110
    - 111
    - 116
    - 123
    - 124
    - 126
    - 127
    - 128
    - 129
    - 130
    - 131
    - 132
    - 133
    - 134
    - 135
    - 136
    - 138
    - 139
    - 140
    - 141
    - 142
    - 143
    - 145
    - 146
    - 147
    - 148
    - 149
    - 150
    - 151
    - 152
    - 153
    - 154
    - 157
    - 158
    - 161
    - 162
    - 163
    - 164
    - 165
    - 167
    - 170
    - 171
    - 172
    - 173
    - 174
    - 175
    - 183
    - 184
    - 185
    - 186
    - 187
    - 188
    - 189
    - 190
    - 191
    - 192
    - 193
    - 194
    - 195
    - 196
    - 197
    - 207
    - 208
    - 218
    - 325
    - 326
    - 327
    - 354
  break:
    whitelist:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 35
    - 37
    - 38
    - 39
    - 40
    - 41
    - 42
    - 44
    - 45
    - 47
    - 48
    - 50
    - 51
    - 53
    - 54
    - 55
    - 56
    - 57
    - 58
    - 59
    - 60
    - 61
    - 63
    - 64
    - 65
    - 66
    - 67
    - 68
    - 69
    - 70
    - 71
    - 72
    - 73
    - 75
    - 77
    - 78
    - 79
    - 80
    - 81
    - 82
    - 83
    - 84
    - 85
    - 86
    - 91
    - 92
    - 93
    - 94
    - 96
    - 98
    - 99
    - 100
    - 101
    - 102
    - 103
    - 104
    - 105
    - 106
    - 107
    - 108
    - 109
    - 110
    - 111
    - 116
    - 123
    - 124
    - 126
    - 127
    - 128
    - 129
    - 130
    - 131
    - 132
    - 133
    - 134
    - 135
    - 136
    - 138
    - 139
    - 140
    - 141
    - 142
    - 143
    - 145
    - 146
    - 147
    - 148
    - 149
    - 150
    - 151
    - 152
    - 153
    - 154
    - 157
    - 158
    - 161
    - 162
    - 163
    - 164
    - 165
    - 167
    - 170
    - 171
    - 172
    - 173
    - 174
    - 175
    - 183
    - 184
    - 185
    - 186
    - 187
    - 188
    - 189
    - 190
    - 191
    - 192
    - 193
    - 194
    - 195
    - 196
    - 197
    - 207
    - 208
    - 218
    - 325
    - 326
    - 327
    - 354

# Which entities will be left in the map after rollback
entities:
  keep:
    - MinecartRideable
    - MinecartFurnace
    - MinecartCommandBlock
    - MinecartSpawner
    - MinecartHopper
    - MinecartChest
    - ArmorStand
    - Painting
    - ItemFrame
#    - EnderCrystal
#    - Boat
#    - FallingSand
#    - WitherSkull
#    - LeashKnot

#How many blocks to rollback per-tick
#The higher this settings the fast each
#arena will be reset but will cause more
#lag
rollback:
  per-tick: 100
 

#Settings for when the game nears end. This runs
#when there are only x amount of players
#remaining. If place chest is enabled then
#when the player limit is reached, a chest
#will be placed inside the radius of every 
#remain player containing random items for 
#that player. If fire-lighting is enabled
#then a lighting strike will be fired at the
#location of each player every x seconds to
#notify the other players of their location
endgame:
  players: 3
  fire-lighting:
    enabled: true
    interval: 20
  
  
#If enabled, after x amount of time, each player
#remaing will be teleported to the center of the
#arena for a death match. If they have not been 
#killed after killtime, the game will end.
deathmatch:
  enabled: false
  time: 30
  killtime: 5
  

#If enabled, winner gets the specified reward
# Items are defined as 
#    itemnumber, amount, durabilty, enchantments, name
# Example: diamond sword with 1 item, full durabilty, shaprness 4, knockback 2 and the name killer
#     276, 1, 0, sharpness: 4 knockback: 2, killer
reward:
 enabled: true
 contents:
  - 'amount:5000'
  
  
#Settings for connecting to and 
#SQL server. These settings will
#be used for  the online webstats
#Prefix is what all tables used for 
#SurvivalGames will be
#prefixed with. This should stay the same
#for most cases.
sql:
  host: 'localhost'
  port: 3306
  user: 'root'
  pass: ''
  database: 'survivalgames'
  prefix: 'sg_'

  
  
###########################################################
###########################################################
  
  
#Settings for the webstats. If enabled, stats 
#such as k/d record, wins, win streaks, kill
#streaks, etc. will be saved. 

stats:
  enabled: false
  webserver:
    enabled: false
    port: 880
  points:
    kill: 10
    win: 100
    position: 7
    killstreak:
      base: 10
      multiplier: 2
  killstreak:
    level1: '&e{player}&7 got a Double Kill!'
    level2: '&e{player}&9 got a Multi Kill!'
    level3: '&e{player}&5 got an Ultra Kill!'
    level4: '&e{player}&4 got an Unbelievable Kill!'
    level5: '&e{player}&a&kii&4&l Unbelievable+!&a&kii'

**Comment by josuedanielbust** [comment]
Review your words properties and too if you allow the pvp through worldguard

**Comment by xan61789** [comment]
I have solved my problem
Sharing the same issue by the way to know

I am a Chinese translation of this issue is caused by an error
The following configuration is said to
protect players after the start time
rather than per game with the longest time
I was mistaken to appear puzzled

-------------------------------------------------------------------------
#If enabled, after x amount of time, each player
#remaing will be teleported to the center of the
#arena for a death match. If they have not been 
#killed after killtime, the game will end.
deathmatch:
  enabled: true
  time: 1800
  killtime: 600
-------------------------------------------------------------------------
