### ISSUE TITLE
Optional initial chest fill

### ISSUE THREAD

**Issue by sshipway** [ThunderGemios10/Survival-Games#6]
Have a boolean option in the config.yml to trigger an initial chest load at game start.  This will prevent people from learning where good items are and always going there... and will allow maps where all chests are empty initially.

**Comment by ThunderGemios10** [comment]
Same answer for #5

**Comment by sshipway** [comment]
Seems this option is already there ... but with a caveat.  The randomisation is fixed to only adding level-1 items.  See other error.

**Comment by sshipway** [comment]
Fixed in #10 , but needs documentation
