### ISSUE TITLE
/sg Addwall issue

### ISSUE THREAD

**Issue by Strikenz** [ThunderGemios10/Survival-Games#62]
Hey there!

I'm not sure what I'm quite doing wrong so hopefully it's just me and not an error, When trying to to /sg addwall, I'm returned with the "Added Lobby Wall" but nothing happens, the signs stay blank. (I'm not too fussed about the wall, I'm more trying to figure out how to get custom arena names) If anyone knew how to do this I'd appreciate the info xD Thanks ~~

**Comment by ThunderGemios10** [comment]
@Strikenz Hi there! Can you tell me what version of Spigot are you using?

Also, are there any errors in the console log?

If there are no errors, make sure to properly select the lobby signs with WorldEdit.

**Comment by Strikenz** [comment]
![image](https://user-images.githubusercontent.com/33733194/37486209-ed1c8e3c-28e1-11e8-888a-73433d83d085.png)
^ The one we're currently using
Weirdly no errors in console, and I have a WorldEdit CUI so it was definitely selected.

Appreciate the help again :) Thanks.

**Comment by Strikenz** [comment]
Welp, I have absolutely zero Idea what changed in the last day, but the addwall is working now, Now to just figure out how to make the arena name customised >.<

**Comment by ThunderGemios10** [comment]
@Strikenz Good to hear that things have worked out.

**Comment by Strikenz** [comment]
Would you still happen to know how to edit an arena name by chance?
