### ISSUE TITLE
Damage

### ISSUE THREAD

**Issue by H2ZeroFX** [ThunderGemios10/Survival-Games#67]
So what's with the end game? We are having a bug where you are full diamond with enchants and everything, but you can die from an arrow at six hearts. Plus it's really annoying that you instantly teleport to lobby, instead of fireworks and what not from other plugins.

**Comment by MWHunter** [comment]
In DeathEvent, the author should use .getFinalDamage() instead of .getDamage()

**Comment by Remyk1** [comment]
Fixed by e1809c68d082e9a7f886b0e11cf0a47b5514780b
