### ISSUE TITLE
Suggestion: Add support for FAWE

### ISSUE THREAD

**Issue by KarlOfDuty** [ThunderGemios10/Survival-Games#71]
As fawe is way more efficient than normal worldedit and also has a lot more features it would be nice if it was also supported here. Currently trying to define an arena using fawe instead of worldedit causes an exception to be thrown.

I have only tried this on the 1.13 version though, so this may be different as fawe used to be installed alongside normal worldedit before then.

**Comment by Remyk1** [comment]
![Knipsel](https://user-images.githubusercontent.com/32412516/56913292-8a168c80-6ab1-11e9-90f9-9c61fe78267a.PNG)
This is a probably a issue with FAWE as it should be compatible with WorldEdit.

Also could you send some more information on the exception you're getting so i can verify that it is not a problem with survival games.

**Comment by Remyk1** [comment]
Also make sure you are running the newest version of FAWE

**Comment by KarlOfDuty** [comment]
I am running `FastAsyncWorldEdit-bukkit-1.13.104` and here is the exception:

![image](https://user-images.githubusercontent.com/18099825/56918162-96a0e200-6abd-11e9-8048-f9b4101a5091.png)

**Comment by Remyk1** [comment]
Does it work with normal worldedit?

**Comment by KarlOfDuty** [comment]
Yes it does.

**Comment by Remyk1** [comment]
I just tried on spigot 1.13.2 with FAWE 1.13.104.

works for me (no errors when doing "/sg createarena" like shown in your screenshot)

**Comment by Remyk1** [comment]
could you maybe try getting the latest version of survival games for 1.13 [here](https://github.com/Remyk1/Survival-Games/releases/tag/v.0.7.1) as i do recall updating that release after i first uploaded it.

**Comment by KarlOfDuty** [comment]
I am running on paperspigot, not spigot so that might be a thing. I downloaded the plugin yesterday so if it hasn't changed since then it should be latest.

**Comment by Remyk1** [comment]
![Knipsel](https://user-images.githubusercontent.com/32412516/56951895-3fd8ee00-6b39-11e9-8f14-a534985e4a85.PNG)
So tried on paper with these plugins installed Plugins (8): FastAsyncWorldEdit, LuckPerms, Multiverse-Core*, SpawnOnJoin*, SurvivalGames*, ViaVersion*, WorldEdit, WorldGuard

and it works fine.

**Comment by Remyk1** [comment]
Perhaps try removing all other plugins and see if it works with just FAWE and Survival-Games

**Comment by KarlOfDuty** [comment]
I thought I did that but now I'm not sure actually.

**Comment by KarlOfDuty** [comment]
Hmm, it seems there was some issue with Paper build 620 as it works now without issue when I updated to 624. Thanks for the help though!
