### ISSUE TITLE
Item ids

### ISSUE THREAD

**Issue by KarlOfDuty** [ThunderGemios10/Survival-Games#72]
Quick question, are we still supposed to use numeric item ids in the config here? (1.13 plugin version)
![image](https://user-images.githubusercontent.com/18099825/58767646-ebd58500-858e-11e9-828a-b66def9059fc.png)

**Comment by Remyk1** [comment]
No, if you are using the update version of the plugin(v7.0.0 or higher) you can't use numeric item ids anymore.

**Comment by Remyk1** [comment]
Could you close this issue?
