### ISSUE TITLE
signs moving

### ISSUE THREAD

**Issue by Minecraftsim** [ThunderGemios10/Survival-Games#76]
**Describe the bug**
when i finish a game sometimes one of the signs move or disappear
**To Reproduce**
Explain how the steps to reproduce the behavior.
so i do /sg add wall 1 and do it again on a diffrent line /sg addwall 2 when i go into 1 and then win or lose the sign would move or disapper?
**Expected behavior**

**Screenshots**

**Errors**
If applicable, also add the errror getting.

**Specfiy which versions your using**
 - Plugin version.
 - Spigot version.
 - WorldEdit version.

**Additional context**

**Comment by Minecraftsim** [comment]
im 1.12.2!

**Comment by Remyk1** [comment]
What is your plugin version?

**Comment by Minecraftsim** [comment]
v0.6.7 (Upto 1.12.2)

**Comment by Minecraftsim** [comment]
never mined im just gonna a use npc but i always have to disable then enable them to play again which is really annoying!

**Comment by Minecraftsim** [comment]
sorry for spelling :(

**Comment by Remyk1** [comment]
I can't seem to reproduce this in the newest version so i'll just close this issue for now.
