### ISSUE TITLE
Radom Join Command

### ISSUE THREAD

**Issue by Minecraftsim** [ThunderGemios10/Survival-Games#78]
Hey can you make a random join thing so i can make one npc that joins all my maps!

**Comment by Minecraftsim** [comment]
or sign!

**Comment by Minecraftsim** [comment]
just a command like /sg randomjoin That Would Be great if can if not its fine.

**Comment by Remyk1** [comment]
Pure random or some logic to put you in the best game?

**Comment by Remyk1** [comment]
I added a randomJoin command to my fork 
[https://github.com/Remyk1/Survival-Games/releases/tag/v0.7.5](url)
Also you can create a sign like this

```
[SurvivalGames]

Auto assign

```

**Comment by Remyk1** [comment]
I have merged this change into this repository(see #81).

**Comment by Minecraftsim** [comment]
Thanks for adding it I’m really happy thanks!
