### ISSUE TITLE
Support for 1.8 on newer builds

### ISSUE THREAD

**Issue by raymondjxu** [ThunderGemios10/Survival-Games#80]
**Is your feature request related to a problem? Please describe.**
Many players like 1.8 pvp.

**Describe the solution you'd like**
Have the new jars compatible with out servers.

**Comment by Remyk1** [comment]
Have you tried. any errors?

If its 1.8 pvp you're after can't you use a plugin that remove the cooldown, adds blocking, etc?

**Comment by raymondjxu** [comment]
Closing issue. I’ve found another plugin that seems less buggy with messages and had native support for 1.8. Your plugin works great in newer versions, but it isn’t the best fit for the current server architecture I’m using.

**Comment by raymondjxu** [comment]
(Due to how the minigame bungee system is coded it absolutely requires for all of the minigame backend servers to be 1.8.8 native)
