### ISSUE TITLE
problem with config/bandage not disappearing

### ISSUE THREAD

**Issue by Gorbiel** [ThunderGemios10/Survival-Games#89]
**Describe the bug**
1. Players can't place or destroy blocks. I tried editing the config. I tried with and without "minecraft:" - uppercase and lowercase (for example minecraft:oak_leaves, oak_leaves, OAK_LEAVES)
2. After using paper named "bandage" the item is still in player's inventory, so he can spam and use it continuously without consuming the paper
 
I attached the config files.
[configs.zip](https://github.com/ThunderGemios10/Survival-Games/files/4349631/configs.zip)

**Specfiy which versions your using**
 - Plugin version. 7.5.0-SNAPSHOT
 - Spigot version. - PAPER #132 for 1.15.2
 - WorldEdit version. 7.1.0

**Comment by Remyk1** [comment]
Are there any errors in console?
1. The names should match https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html preferably uppercase (this issue might be related to #83 #84 )
2. Does it work with plain paper (no name, enchantments)?

**Comment by Gorbiel** [comment]
So I switched to .jar from issue #83 and it seems to show up in console, but there's another issue with that:
[SurvivalGames] [Debug] PlaceEvent: read : [COBBLESTONE, TORCH, CAKE, OAK_PLANKS, OAK_LEAVES, MELON]
[20:02:35 INFO]: [SurvivalGames] [Debug] BreakEvent: read : [COBBLESTONE, TORCH, CAKE, OAK_PLANKS, OAK_LEAVES, MELON]

It ignores the block-place whitelist and uses block-break whitelist for both categories.
This is my config:
block:
  place:
    whitelist:
    - COBBLESTONE
    - COBWEB
    - TORCH
    - CAKE
    - OAK_PLANKS
  break:
    whitelist:
    - COBBLESTONE
    - TORCH
    - CAKE
    - OAK_PLANKS
    - OAK_LEAVES
    - MELON

**Comment by Gorbiel** [comment]
With jar file from spigot there was "null" everywhere (PlaceEvent: read : [null, null, null, null, null, null])

**Comment by Remyk1** [comment]
#90 should fix this issue

**Comment by Gorbiel** [comment]
Thank you very much, it took me a while to learn how to build this thing but now it seems to work. I can't test it now but when I do I'll close this thread

**Comment by Remyk1** [comment]
Which repo did you clone because i didn't merge #90 into this repo yet.
If you want to test it you can clone https://github.com/Remyk1/Survival-Games.git
If you have maven installed just open a shell(cmd or bash) and run `mvn clean install` in the directory where the pom.xml file is.

**Comment by Gorbiel** [comment]
I cloned it from your repo and built it using maven in eclipse. The plugin detects config correctly but still nobody can place/break anything

**Comment by Gorbiel** [comment]
Here is my latest log and all the config files. I made sure that worldguard doesn't interfere with Survival Games and tested with and without op on the server.
[latest.zip](https://github.com/ThunderGemios10/Survival-Games/files/4357306/latest.zip)

**Comment by Gorbiel** [comment]
But the good news is that bandages work flawlessly

**Comment by Remyk1** [comment]
Ok i added an excessive amount of debugging to place event 
[Survival-Games.zip](https://github.com/ThunderGemios10/Survival-Games/files/4359202/Survival-Games.zip)

**Comment by Gorbiel** [comment]
[latest.log](https://github.com/ThunderGemios10/Survival-Games/files/4359993/latest.log)

**Comment by Remyk1** [comment]
Can you try this jar [Survival-Games.zip](https://github.com/ThunderGemios10/Survival-Games/files/4360894/Survival-Games.zip)

**Comment by Gorbiel** [comment]
[latest.log](https://github.com/ThunderGemios10/Survival-Games/files/4361183/latest.log)
Unfortunately there's no change

**Comment by Remyk1** [comment]
I think this should fix it 
[Survival-Games.zip](https://github.com/ThunderGemios10/Survival-Games/files/4362803/Survival-Games.zip)

**Comment by Gorbiel** [comment]
Finally! Everything's working. Thank you very much!

I have a suggestion - after the end of the game xp also gets reset. And maybe if you win you earn some server money (the vault one). I would try to add this with pull request, but I don't know java
