### ISSUE TITLE
Permissions issues still persist?

### ISSUE THREAD

**Issue by loooukas** [ThunderGemios10/Survival-Games#92]
I was running 1.8.8 Spigot and my permissions did not work, I've updated to 1.12.2 now: 
https://i.imgur.com/sbsw8aT.png

still, a non-op player cannot join a lobby through the join signs or commands (It's probably me messing up the permissions, not the plugin though)

Any support would be greatly appreciated :D

Plugins used that relate to this issue:
SG plugin
LuckPerms

**Comment by Remyk1** [comment]
Can you try explicitly adding the different arena join permissions.
For example "sg.arena.join.0" and  "sg.arena.join.1"

**Comment by loooukas** [comment]
no luck :( 
Should I be creating a new permissions class for this (other than default)?

**Comment by Remyk1** [comment]
Actually how did you make those signs because the signs from this plugin don't look like that.
So i had a look around and found this [plugin](https://www.spigotmc.org/resources/survivalgames.1351/),  the signs seem very similar.
If you are using the above plugin, then it looks like you should use the "sg.join" permission instead.

**Comment by loooukas** [comment]
Thats quite odd, ill look into it thanks for the information, whats odd is I only remember using this exact spigot link lmao

**Comment by loooukas** [comment]
(by this exact spigot link i mean the one that links you to this github)

**Comment by Remyk1** [comment]
To check if this is the correct plugin open the jar file with winrar or 7zip and open the plugin.yml file to see the author.

**Comment by loooukas** [comment]
okay ive been testing again with multiple reloads, etc it seems to be working :D tysm
