### ISSUE TITLE
Plugin Survival games! 

### ISSUE THREAD

**Issue by Agustin32076puc** [ThunderGemios10/Survival-Games#94]
I have a plugin that I want you to try, it is from the MINECRAFT version 1.7.10, but it has functions that I like.
Maybe I can pay you to update it!

We could talk and coordinate? Whatsapp; Skype? 

Speak Spanish

Thanks :) 

If you like, I pass you the files of a server already configured with this plugin. So you can see it

**Comment by Remyk1** [comment]
This is not the place for this.
You could look at spigot formus https://www.spigotmc.org/forums/hiring-developers.55/
or helpchat discord https://helpch.at/discord
